---
- hosts: all
  become: yes
  vars:
# Set to none, maintenance_dc1, maintenance_dc2
# none - All up
# maintenance_dc1 - DC1 backends down
# maintenance_dc2 - DC2 backends down
    backend_maintenance: none
#Set to first to first start
    setup: first_
  roles:
    - ansible-nginx
    